# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container to /backend
WORKDIR /backend

# Copy the package.json and package-lock.json to the container
COPY package*.json ./

# Install the app dependencies inside the container
RUN npm install

# Copy the server code into the container
COPY server.js .

# Start the server
CMD ["node", "server.js"]
